name: Build and Push huesped Image

on:
  push:
    branches: [ main, test ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Necesario para publicar en GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Instalar Node y construir la aplicación antes de crear la imagen
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
    
      - name: Install dependencies
        run: npm install
    
      - name: Build project
        run: npm run build

      # Ahora configuramos docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Determinar el nombre de la imagen según la rama
      - name: Determine image name based on branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "IMAGE_NAME=huesped" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=huesped-test" >> $GITHUB_ENV
          fi

      - name: Build image with docker compose
        run: docker compose build

      - name: Tag image
        run: docker tag huesped:latest ghcr.io/th-the-hoster/${{ env.IMAGE_NAME }}:latest

      - name: Push image to GHCR
        run: docker push ghcr.io/th-the-hoster/${{ env.IMAGE_NAME }}:latest
